### ISSUE TITLE
Definitely a good project.

### ISSUE THREAD

**Issue by mozdevcontrib** [adversarialtools/apple-telemetry#10]
Reminds me of this: https://gitlab.com/intr0/AppleBlock

Seems we both found many overlapping "phone home" Apple DNS requests. Initially started it as a hobby project to protect people from having a specific anti-ad app from being removed from people's devices by Apple. Moved it to GitLab some time later. Good to see something similar being actively maintained. 👍🏼

**Comment by cedws** [comment]
Yep, nice to see that others are paying attention to the traffic transmitted by Apple. I've added a link to your project in the README.

I'd suggest merging our lists but I'm not sure that the licensing is compatible.

**Comment by mozdevcontrib** [comment]
I just did the same on AppleBlock's README. Changed license to GPLv2 for compatibility with your GPLv3 License.
