### ISSUE TITLE
I found more Apple Domains that aren't in the list

### ISSUE THREAD

**Issue by MrWaste** [adversarialtools/apple-telemetry#12]
I don't know if you are wanting more domains but I just found some more.. I saw you updated the list 9 days ago so might as well help out. :)
I was doing a search with the dns "e673.dsce9.akamaiedge.net" and found more alternative names that weren't in the list. I also saw "e4478.a.akamaiedge.net" but this one wasn't on the list and that's why I was digging even more because I wanted to know what it is and why is it need for what traffic. 
The list has duplicates but just use a duplicate remover to remove them. 
[https://www.textfixer.com/tools/remove-duplicate-lines.php](url)

Also, I might as well ask, have you ever done any reverse dns looksups or back grounds checks to see what kind of traffic is going where and why to these domains are need or used? If so it would much appreciated if you could share you knowledge to help out one another!!
[https://threatintelligenceplatform.com/report/e673.dsce9.akamaiedge.net/RWlLCuGgLD](e673.dsce9.akamaiedge.net)
[https://threatintelligenceplatform.com/report/e4478.a.akamaiedge.net/DJmj8B9bhw](e4478.a.akamaiedge.net)

Edit:
When I add this list there was 1070 and now there is 1123 total. Check it out vs the normal list.
Last, I was wondering if I could be apart of this project :)
[https://github.com/MrWaste/apple-telemetry](url)

Sincerely,
Mr. Waste

web-experience.itunes.apple.com
vpp-app.itunes.apple.com
vocabulary.itunes.apple.com
videos.apple.com
uts-preview.itunes.apple.com
uts-api-siri.itunes.apple.com
upp.itunes.apple.com
tv.apple.com
tf-feedback.itunes.apple.com
sync.itunes.apple.com
su.itunes.apple.com
store.mzstatic.com
sp.itunes.apple.com
sitemaps.itunes.apple.com
siri-search.itunes.apple.com
sf-api-token-service.itunes.apple.com
search.itunes.apple.com
se.itunes.apple.com
se-edge.itunes.apple.com
sb.tv.apple.com
sb.music.apple.com
s5.mzstatic.com
s4.mzstatic.com
s3.mzstatic.com
s2.mzstatic.com
s1.mzstatic.com
s.mzstatic.com
radio.itunes.apple.com
radio-services.itunes.apple.com
radio-quickplay.itunes.apple.com
radio-activity.itunes.apple.com
podcasts.apple.com
pd.itunes.apple.com
pcr.apple.com
partiality.itunes.apple.com
music.apple.com
metrics.mzstatic.com
itunesu.itunes.apple.com
itunes.apple.com
itc.mzstatic.com
is5-ssl.mzstatic.com
is4-ssl.mzstatic.com
is3-ssl.mzstatic.com
is2-ssl.mzstatic.com
is1-ssl.mzstatic.com
init.itunes.apple.com
finance-app.itunes.apple.com
files.itunes.apple.com
embed.itunes.apple.com
edge.itunes.apple.com
edge-search.itunes.apple.com
dzc-metrics.mzstatic.com
desktop-store.itunes.apple.com
desktop-music.itunes.apple.com
desktop-music-legacy.itunes.apple.com
configuration.apple.com
carrierbundle.itunes.apple.com
books.apple.com
bookkeeper.itunes.apple.com
bag.itunes.apple.com
b5.mzstatic.com
b4.mzstatic.com
b3.mzstatic.com
b2.mzstatic.com
b1.mzstatic.com
apps.mzstatic.com
apps.apple.com
api.videos.apple.com
api.podcasts.apple.com
api.music.apple.com
api.itunes.apple.com
api.edu.apple.com
api.books.apple.com
api.apps.apple.com
api-edge.apps.apple.com
amp-api.podcasts.apple.com
amp-api-search-edge.apps.apple.com
amp-api-edge.apps.apple.com
accertify.mzstatic.com
a5.mzstatic.com
a4.mzstatic.com
a3.mzstatic.com
a2.mzstatic.com
a1.mzstatic.com

**Comment by cedws** [comment]
Thanks! More domains are always appreciated. I've just pushed a new release with credits to you.

>The list has duplicates but just use a duplicate remover to remove them.
https://www.textfixer.com/tools/remove-duplicate-lines.php

There's a Makefile in the repo which will take care of duplicates. If you don't know how to use this then don't worry about it, I can take care of removing duplicates.

>have you ever done any reverse dns looksups or back grounds checks

I haven't really inspected the traffic but I would expect most of it is TLS encrypted, so there won't be much to find. There's a very basic overview of the domains purposes [here](https://github.com/adversarialtools/apple-telemetry/wiki/Domains).

>Last, I was wondering if I could be apart of this project :)

Well, it's open source, so anybody can be a part of it :smile:. If you want to be added as a contributor, let's talk about it - email me at cedw@pm.me.
