### ISSUE TITLE
Domain to remove for update ?

### ISSUE THREAD

**Issue by aelisya** [adversarialtools/apple-telemetry#14]
Hello, 

I create a dns side protection, and i want to lock apple domain, but i want to let the possibility to update since i dont touche often the dns (i will lock it on the client side the store domain and ios update), but can you tell me witch domain i have to remove to autorise only these update ?

edit : i know there is a wiki, but app store isn't in it ^^

Thanks

**Comment by aelisya** [comment]
seems this git is not monitored so i close

**Comment by cedws** [comment]
Hi, you might need to remove `*.mesu.apple.com`. If that doesn't work, play around a bit.
