### ISSUE TITLE
Where can i find the list? 

### ISSUE THREAD

**Issue by r0my** [adversarialtools/apple-telemetry#17]
Hello! I want to try your blocking list, but i can not find the list for dnscloack you provided in the first post. Can you help me? There are some files in assets, but when i download it with ios safari downloader, i can‘t open the files. 

Romy :o)

**Comment by cedws** [comment]
Hey, not really sure what you mean, sorry. All the lists are under [Releases](https://github.com/adversarialtools/apple-telemetry/releases).
