### ISSUE TITLE
Please add the domains to block list

### ISSUE THREAD

**Issue by Picallo-svg** [adversarialtools/apple-telemetry#7]
daypass.api-glb-sto.smoot.apple.com
p46-fmf.icloud.com
p46-fmip.icloud.com
p46-contacts.icloud.com
p46-keyvalueservice.icloud.com
p46-fmfmobile.icloud.com
p46-avaliability.icloud.com
p46-quota.icloud.com
init.push.apple.com
mesu-cdn.origin-apple.com.akadns.net
fmip.fe.apple-dns.net
quota.fe.apple-dns.net
e10489.a.akamaiedge.net
s.mzstatic.com
is-ssl.mzstatic.com.itunes-apple.com.akadns.net
p23-buy.itunes.apple.com
static.icloud.com.edgekey.net
e673.dsce9.akamaiedge.net
configuration.apple.com.akadns.net
eu-irl-00001.s3.dualstack.eu-west-1.amazonaws.com
me-apple-dns.net
gcs-eu-00002.content-storage-download.googleapis.com
e6858.dsce9.akamaiedge.net
www.apple.com.edgekey.net
sf-api-token-service.itunes.apple.com
api.apps.apple.com
api-edge.apps.apple.com
configuration.ls.apple.com
health.apple.com
app.smartmailcloud.com
news.apple.com
is1-ssl.mzstatic.com
is2-ssl.mzstatic.com
is3-ssl.mzstatic.com
is4-ssl.mzstatic.com
is5-ssl.mzstatic.com

**Comment by cedws** [comment]
Thank you for your contribution. I have chosen to exclude `app.smartmailcloud.com` because I couldn't link it to Apple or iCloud in any way. The other domains have been added and a new release has been created.

**Comment by Picallo-svg** [comment]
Thank you for fast solving! Today I was blocked some new apple domains:

apps.mzstatic.com
api-apps-lb.itunes-apple.com.akadns.net
play.itunes.apple.com.edgesuite.net
p23-buy.itunes-apple.com.akadns.net
apple.news

**Comment by haze-megatf** [comment]
Just curious what's the evidence that `eu-irl-00001.s3.dualstack.eu-west-1.amazonaws.com` is apple telemetry?
Thanks
