### ISSUE TITLE
Add new domains to blacklist

### ISSUE THREAD

**Issue by Picallo-svg** [adversarialtools/apple-telemetry#8]
apps.mzstatic.com
api-apps-lb.itunes-apple.com.akadns.net
play.itunes.apple.com.edgesuite.net
p23-buy.itunes-apple.com.akadns.net
apple.news
30.courier-push-apple.com.akadns.net
mt-ingestion-service-pv.itunes.apple.com
gsp85-ssl.ls.apple.com

**Comment by cedws** [comment]
Thanks again for the contribution :+1: new release has been created.

**Comment by Picallo-svg** [comment]
Thank for quick release!
Please, tell me where be better to write new lists of domains - here or I must create a new Issue request?

**Comment by cedws** [comment]
You can send a PR if you’re up for it (although you would need to run `make cleanup` locally first) - you’d get proper credit for your contributions that way too. I don’t mind if you leave a comment with more domains you find and let me push them either. It’s up to you.

**Comment by Picallo-svg** [comment]
i collect a new list of domains via firewall:

apple-finance.query.yahoo.com
c.apple.news
basejumper.apple.com
apsu.apple.com
commnat-cohort-gc.ess.apple.com
commnat-main-gc.ess.apple.com
api.apple-cloudkit.com
api.apple-cloudkit.fe.apple-dns.net
cdsassets.apple.com
init.ess.apple.com.edgesuite.net
3.courier-push-apple.com.akadns.net
4.courier-push-apple.com.akadns.net
5.courier-push-apple.com.akadns.net
6.courier-push-apple.com.akadns.net
7.courier-push-apple.com.akadns.net
8.courier-push-apple.com.akadns.net
9.courier-push-apple.com.akadns.net
11.courier-push-apple.com.akadns.net
13.courier-push-apple.com.akadns.net
14.courier-push-apple.com.akadns.net
15.courier-push-apple.com.akadns.net
16.courier-push-apple.com.akadns.net
17.courier-push-apple.com.akadns.net
18.courier-push-apple.com.akadns.net
19.courier-push-apple.com.akadns.net
21.courier-push-apple.com.akadns.net
22.courier-push-apple.com.akadns.net
23.courier-push-apple.com.akadns.net
24.courier-push-apple.com.akadns.net
25.courier-push-apple.com.akadns.net
26.courier-push-apple.com.akadns.net
27.courier-push-apple.com.akadns.net
29.courier-push-apple.com.akadns.net
32.courier-push-apple.com.akadns.net
33.courier-push-apple.com.akadns.net
34.courier-push-apple.com.akadns.net
35.courier-push-apple.com.akadns.net
36.courier-push-apple.com.akadns.net
38.courier-push-apple.com.akadns.net
41.courier-push-apple.com.akadns.net
42.courier-push-apple.com.akadns.net
49.courier-push-apple.com.akadns.net
50.courier-push-apple.com.akadns.net
