### ISSUE TITLE
Add new domains

### ISSUE THREAD

**Issue by Picallo-svg** [adversarialtools/apple-telemetry#9]
any-appleweather-cache.internal.query.a03.yahoodns.net
api.apple-cloudkit.com
api.apple-cloudkit.fe.apple-dns.net
apple-finance.query.yahoo.com
appleid.cdn-apple.com
apple-mobile.query.yahooapis.com
appleweather-cache.internal.query.g03.yahoodns.net
apptrailers.itunes.apple.com.c.footprint.net
apsu.apple.com
ax.phobos.apple.com.edgesuite.net
basejumper.apple.com
c.apple.news
cdsassets.apple.com
commnat-cohort-gc.ess.apple.com
commnat-main-gc.ess.apple.com
configuration.apple.com.edgekey.net
gspe19.ls.apple.com
gspe21.ls.apple.com
iadsdk.apple.com.edgekey.net
init.ess.apple.com.edgesuite.net
init.gc.apple.com.edgesuite.net
init-p01md.apple.com.edgesuite.net
internalcheck.apple.com
isg-apple.com.akadns.net
itunes.apple.com.edgekey.net
mzuserxp.itunes-apple.com.akadns.net
p47-buy.itunes.apple.com
pancake.apple.com.edgekey.net
pd-st.itunes.apple.com
play.itunes-apple.com.akadns.net
ssl.apple.com
static.gc.apple.com.edgekey.net
static.ips.apple.com
swcdn.apple.com
3.courier-push-apple.com.akadns.net
4.courier-push-apple.com.akadns.net
5.courier-push-apple.com.akadns.net
6.courier-push-apple.com.akadns.net
7.courier-push-apple.com.akadns.net
8.courier-push-apple.com.akadns.net
9.courier-push-apple.com.akadns.net
11.courier-push-apple.com.akadns.net
13.courier-push-apple.com.akadns.net
14.courier-push-apple.com.akadns.net
15.courier-push-apple.com.akadns.net
16.courier-push-apple.com.akadns.net
17.courier-push-apple.com.akadns.net
18.courier-push-apple.com.akadns.net
19.courier-push-apple.com.akadns.net
21.courier-push-apple.com.akadns.net
22.courier-push-apple.com.akadns.net
23.courier-push-apple.com.akadns.net
24.courier-push-apple.com.akadns.net
25.courier-push-apple.com.akadns.net
26.courier-push-apple.com.akadns.net
27.courier-push-apple.com.akadns.net
29.courier-push-apple.com.akadns.net
32.courier-push-apple.com.akadns.net
33.courier-push-apple.com.akadns.net
34.courier-push-apple.com.akadns.net
35.courier-push-apple.com.akadns.net
36.courier-push-apple.com.akadns.net
38.courier-push-apple.com.akadns.net
41.courier-push-apple.com.akadns.net
42.courier-push-apple.com.akadns.net
49.courier-push-apple.com.akadns.net
50.courier-push-apple.com.akadns.net
a1047.phobos.apple.com
a1076.phobos.apple.com
a1109.phobos.apple.com
a1190.phobos.apple.com
a1191.phobos.apple.com
a1257.phobos.apple.com
a1270.phobos.apple.com
a1364.phobos.apple.com
a1426.phobos.apple.com
a1437.phobos.apple.com
a1473.phobos.apple.com
a1484.phobos.apple.com
a149.phobos.apple.com
a1500.phobos.apple.com
a1566.phobos.apple.com
a1650.phobos.apple.com
a1715.phobos.apple.com
a1724.phobos.apple.com
a1808.phobos.apple.com
a1816.phobos.apple.com
a1850.phobos.apple.com
a1861.phobos.apple.com
a1891.phobos.apple.com
a247.phobos.apple.com
a26.phobos.apple.com
a284.phobos.apple.com
a3.phobos.apple.com
a383.phobos.apple.com
a407.phobos.apple.com
a423.phobos.apple.com
a479.phobos.apple.com
a487.phobos.apple.com
a507.phobos.apple.com
a512.phobos.apple.com
a53.phobos.apple.com
a560.phobos.apple.com
a628.phobos.apple.com
a63.phobos.apple.com
a663.phobos.apple.com
a669.phobos.apple.com
a672.phobos.apple.com
a761.phobos.apple.com
a840.phobos.apple.com
a859.phobos.apple.com
a910.phobos.apple.com
a93.phobos.apple.com
a948.phobos.apple.com
a949.phobos.apple.com
a977.phobos.apple.com
a983.phobos.apple.com

**Comment by cedws** [comment]
Thanks again.

I'm wondering if we should just outright block `yahoodns.net` and `akadns.net`. It seems that iOS is too smart and uses these as fallback servers if the DNS query is blocked.

**Comment by Picallo-svg** [comment]
> Thanks again.
> 
> I'm wondering if we should just outright block `yahoodns.net` and `akadns.net`. It seems that iOS is too smart and uses these as fallback servers if the DNS query is blocked.

You're right. Also may be better to block *phobos.apple.com (for example), because looks like apple has infinite number of *phobos subdomains.

I want to find out do the iphone's battery and cpu feel difference between full list of blocked subdomains (like aXXX.phobos.com) and one rule *phobos.apple.com . In first look i suppose that one blocking rule is better, but need to investigate.

Also i need to check some other apps (like Skype) after blocking akadns.net, because they uses it (i don't know is akadns.net a reserve server or main).

Meanwhile i found skype domains in your block list. Is that a mistake?

pipe.prd.skypedata.akadns.net
prd.col.aria.browser.skypedata.akadns.net
prd.col.aria.mobile.skypedata.akadns.net
